[env]
TERM = "xterm-256color"

[terminal.shell]
# Powershell 7
# program = "C:\\Program Files\\PowerShell\\7\\pwsh.exe"
# Powershell 5
program = "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
args = ["-WorkingDirectory ~\\Downloads"]

[font]
normal = { family = "FantasqueSansM Nerd Font", style = "Regular" }
size = 12

[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.9
dynamic_title = false

[general]
import = [
  ".\\catppuccin-latte.toml"
]

[terminal]
